name: garage
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^14.0.1
  intl: any
  talker_flutter: ^4.1.5
  talker_bloc_logger: ^4.1.5
  equatable: ^2.0.5
  formz: ^0.7.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  flutter_svg: ^2.0.10+1
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  slang_build_runner: ^3.30.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 900

        - asset: assets/fonts/rubik_italic/Rubik-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/rubik_italic/Rubik-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/rubik_italic/Rubik-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/rubik_italic/Rubik-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/rubik_italic/Rubik-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/rubik_italic/Rubik-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/rubik_italic/Rubik-BlackItalic.ttf
          style: italic
          weight: 900

    - family: SairaStencilOne
      fonts:
        - asset: assets/fonts/saira_stencil_one/SairaStencilOne-Regular.ttf

  assets:
    - assets/images/
    - assets/icons/
