// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJkXNbZgYTFXLRjjSXtY5IT7asj1zEpV4',
    appId: '1:158604765542:web:0455fea6d628a6cbfac0a7',
    messagingSenderId: '158604765542',
    projectId: 'garage-112',
    authDomain: 'garage-112.firebaseapp.com',
    storageBucket: 'garage-112.appspot.com',
    measurementId: 'G-K16HN8S5FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwjmWzOf96XPhSl0bmm9U3B5xzF90CO_Q',
    appId: '1:158604765542:android:8743b1c37a465ec4fac0a7',
    messagingSenderId: '158604765542',
    projectId: 'garage-112',
    storageBucket: 'garage-112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOA-ntaipOZCRQhQv0dbK3PkNsu7nSQsw',
    appId: '1:158604765542:ios:58e95a72d1a0189dfac0a7',
    messagingSenderId: '158604765542',
    projectId: 'garage-112',
    storageBucket: 'garage-112.appspot.com',
    iosBundleId: 'com.example.garage.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOA-ntaipOZCRQhQv0dbK3PkNsu7nSQsw',
    appId: '1:158604765542:ios:f11bbf3b527854a2fac0a7',
    messagingSenderId: '158604765542',
    projectId: 'garage-112',
    storageBucket: 'garage-112.appspot.com',
    iosBundleId: 'com.example.garage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJkXNbZgYTFXLRjjSXtY5IT7asj1zEpV4',
    appId: '1:158604765542:web:979cff0ee391591cfac0a7',
    messagingSenderId: '158604765542',
    projectId: 'garage-112',
    authDomain: 'garage-112.firebaseapp.com',
    storageBucket: 'garage-112.appspot.com',
    measurementId: 'G-F1RJFFBNJ9',
  );
}
